/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import utilidades.DAOException;

/**
 *
 * @author noemi
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

this.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent evt) {
        int opcion = JOptionPane.showConfirmDialog(
            Login.this,
            "¿Está seguro de que desea cerrar la ventana?\n\n"
            + "Si cierra la ventana, se borrarán los datos ingresados.",
            "Confirmar cierre",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            Login.this.dispose();
        }
    }
});
        
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(false);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setForeground(new java.awt.Color(30,30,30));
        
        aplicarEstiloMaterial(txtUsuario);
        aplicarEstiloMaterial(txtContra);
        
        java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userNodeForPackage(Login.class);
        String usuarioGuardado = prefs.get("usuario", "");
        String contrasenaGuardada = prefs.get("contrasena", "");

        if (!usuarioGuardado.isEmpty()) {
            txtUsuario.setText(usuarioGuardado);
            txtContra.setText(contrasenaGuardada);
            jCheckBox2.setSelected(true); // ← CAMBIO: jCheckBox2 es "Recuerdame"
        }
    }
    
    private void aplicarEstiloMaterial(javax.swing.JTextField campo) {
        campo.setBackground(new Color(255, 255, 255));
        campo.setForeground(Color.WHITE);
        campo.setCaretColor(Color.WHITE);
        campo.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.GRAY));
        
        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(138, 43, 226)));
            }
            
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.GRAY));
            }
        });
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContra = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WhatsApp_Image_2026-09-10_at_6.51.51_PM-removebg-preview(1)(1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 270, 250));

        jButton1.setText("Iniciar sesión");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 100, -1));

        jButton2.setText("Olvidé mi contraseña");
        jButton2.setBorder(null);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 150, -1));

        jCheckBox1.setText("Mostrar contraseña");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 140, -1));

        jCheckBox2.setText("Recuerdame");
        jCheckBox2.addActionListener(this::jCheckBox2ActionPerformed);
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 140, -1));

        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 150, 30));

        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 150, 30));

        txtContra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 150, -1));

        txtUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 150, -1));

        jButton3.setText("Registrarse");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 80, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WhatsApp Image 2026-09-05 at 11.01.51 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 460, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // En el botón de Iniciar Sesión:
        String usuario = txtUsuario.getText().trim();
        String contrasena = new String(txtContra.getPassword());

        if (usuario.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese usuario y contraseña");
            return;
        }

        try {
            DAO.UsuarioDAO dao = DAO.UsuarioDAO.getInstance();

            System.out.println("🔐 Intentando login para: " + usuario);

            if (dao.validarUsuario(usuario, contrasena)) {
                JOptionPane.showMessageDialog(this, "✅ Bienvenido: " + usuario);

                // Ir al menú principal (Producto)
                Presentacion.Producto producto = new Presentacion.Producto();
                producto.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, """
                                                    \u274c Usuario o contrase\u00f1a incorrectos
                                                    Si no tienes cuenta, reg\u00edstrate primero""", 
                    "Error de login", 
                    JOptionPane.ERROR_MESSAGE);
            }

        } catch (HeadlessException | SQLException | DAOException e) {
            System.err.println("💥 Excepción en login: " + e.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Error al validar: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
            if (jCheckBox1.isSelected()) {
        // Si está marcado, muestra la contraseña (quita el carácter de ocultamiento)
        txtContra.setEchoChar((char) 0);
    } else {
        // Si no está marcado, oculta la contraseña con asteriscos
        txtContra.setEchoChar('*');
    }
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
    String correo = JOptionPane.showInputDialog(this,
        "Ingresa tu correo registrado:",
        "Recuperar contraseña",
        JOptionPane.QUESTION_MESSAGE);

    if (correo == null || correo.trim().isEmpty()) return;

    try {
        DAO.UsuarioDAO dao = DAO.UsuarioDAO.getInstance();
        String contrasena = dao.obtenerContrasenaPorCorreo(correo.trim());

        if (contrasena == null) {
            JOptionPane.showMessageDialog(this,
                "No se encontró ninguna cuenta con ese correo.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Generar código de 6 dígitos
        String codigo = String.valueOf((int)(Math.random() * 900000) + 100000);

        // Enviar correo
        enviarCorreo(correo.trim(), codigo);

        // Pedir el código
        String codigoIngresado = JOptionPane.showInputDialog(this,
            "Te enviamos un código a " + correo + "\nIngresa el código:",
            "Verificar código",
            JOptionPane.QUESTION_MESSAGE);

        if (codigo.equals(codigoIngresado)) {
            String nuevaContrasena = JOptionPane.showInputDialog(this,
                "Ingresa tu nueva contraseña:",
                "Nueva contraseña",
                JOptionPane.QUESTION_MESSAGE);
            if (nuevaContrasena != null && nuevaContrasena.length() >= 6) {
                dao.actualizarContrasena(correo.trim(), nuevaContrasena);
                JOptionPane.showMessageDialog(this, "✅ Contraseña actualizada exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "❌ Código incorrecto.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

private void enviarCorreo(String destinatario, String codigo) throws Exception {
 String remitente = "fastsnackrecuperacion@gmail.com";
String clave = "katqrjooaiktoyon";

    java.util.Properties props = new java.util.Properties();
    props.put("mail.smtp.auth", "true");
    props.put("mail.smtp.starttls.enable", "true");
    props.put("mail.smtp.host", "smtp.gmail.com");
    props.put("mail.smtp.port", "587");
    props.put("mail.smtp.ssl.protocols", "TLSv1.2");
    javax.mail.Session session = javax.mail.Session.getInstance(props,
        new javax.mail.Authenticator() {
            @Override
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                return new javax.mail.PasswordAuthentication(remitente, clave);
            }
        });

    javax.mail.Message mensaje = new javax.mail.internet.MimeMessage(session);
    mensaje.setFrom(new javax.mail.internet.InternetAddress(remitente));
    mensaje.setRecipients(javax.mail.Message.RecipientType.TO,
        javax.mail.internet.InternetAddress.parse(destinatario));
    mensaje.setSubject("🔐 Recuperación de contraseña - FastSnack");
    mensaje.setText("Hola,\n\nTu código de recuperación es: " + codigo +
        "\n\nEste código expira en 5 minutos.\n\nFastSnack 🍔");

    javax.mail.Transport.send(mensaje);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Registro registro = new Registro();
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables


}
