/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;
/**
 *
 * @author User
 */
public class loginTrab extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginTrab.class.getName());

    /**
     * Creates new form loginTrab
     */
    public loginTrab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        iniciarsecion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FastSnack-Logintrab");

        jLabel1.setText("BIENVENIDOS QUERIDOS TRABAJADORES");

        jLabel2.setText("Correo electronico o usuario");

        iniciarsecion.setText("salir");
        iniciarsecion.addActionListener(this::iniciarsecionActionPerformed);

        jLabel3.setText("Contraseña");

        jButton1.setText("iniciar sesion");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel4.setText("¿Has olvidado tu contraseña?");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jCheckBox1.setText("Mostrar contraseña");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(usuario, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniciarsecion)))
                        .addGap(0, 347, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addGap(0, 185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarsecion)
                    .addComponent(jButton1))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String correo = usuario.getText().trim();
    String clave = new String(jPasswordField1.getPassword());

    // CORREO DEL TRABAJADOR AUTORIZADO
    String trabajadorAutorizado = "patokechup@gmail.com";

    // CONTRASEÑA DEL TRABAJADOR
    String claveTrabajador = "ivanteamo4ever";

    // 1. CORREO VACÍO
    if (correo.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Por favor, ingresa tu correo electrónico.",
                "Correo requerido",
                JOptionPane.WARNING_MESSAGE);
        usuario.requestFocus();
        return;
    }

    // 2. ESTRUCTURA DEL CORREO
    String patronCorreo =
            "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";

    if (!correo.matches(patronCorreo)) {
        JOptionPane.showMessageDialog(this,
                "El correo no es correcto. Verifica que esté escrito correctamente.",
                "Correo inválido",
                JOptionPane.ERROR_MESSAGE);
        usuario.requestFocus();
        return;
    }

    // 3. COMPROBAR QUE SEA EL CORREO DEL TRABAJADOR
    if (!correo.equalsIgnoreCase(trabajadorAutorizado)) {
        JOptionPane.showMessageDialog(this,
                "Este correo no es válido para un trabajador registrado.",
                "Correo no autorizado",
                JOptionPane.ERROR_MESSAGE);
        usuario.requestFocus();
        return;
    }

    // 4. CONTRASEÑA VACÍA
    if (clave.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Por favor, ingresa tu contraseña.",
                "Contraseña requerida",
                JOptionPane.WARNING_MESSAGE);
        jPasswordField1.requestFocus();
        return;
    }

    // 5. CONTRASEÑA CON MENOS DE 8 CARACTERES
    if (clave.length() < 8) {
        JOptionPane.showMessageDialog(this,
                "La contraseña no es válida. Debe tener mínimo 8 caracteres.",
                "Contraseña inválida",
                JOptionPane.ERROR_MESSAGE);
        jPasswordField1.requestFocus();
        return;
    }

    // 6. CONTRASEÑA FORMADA POR EL MISMO CARÁCTER
    if (clave.matches("(.)\\1+")) {
        JOptionPane.showMessageDialog(this,
                "La contraseña no es válida. No puede estar formada por un mismo carácter repetido.",
                "Contraseña inválida",
                JOptionPane.ERROR_MESSAGE);
        jPasswordField1.requestFocus();
        return;
    }

    // 7. COMPROBAR QUE LA CONTRASEÑA SEA LA CORRECTA
    if (!clave.equals(claveTrabajador)) {
        JOptionPane.showMessageDialog(this,
                "La contraseña es incorrecta. Por favor, inténtalo nuevamente.",
                "Contraseña incorrecta",
                JOptionPane.ERROR_MESSAGE);
        jPasswordField1.requestFocus();
        return;
    }

    // 8. TODO CORRECTO
    Factura factura = new Factura();
factura.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
 String respuesta = JOptionPane.showInputDialog(this,
        "¿Cuál es tu personaje favorito + teamo4ever?",
        "Recuperar contraseña",
        JOptionPane.QUESTION_MESSAGE);

if (respuesta == null) {
    return;
}

respuesta = respuesta.trim();

if (!respuesta.equalsIgnoreCase("Ivanteamo4ever")) {
    JOptionPane.showMessageDialog(this,
            "La respuesta es incorrecta. No se puedes continuar con el acceso.",
            "Verificación fallida",
            JOptionPane.ERROR_MESSAGE);
    return;
}

JOptionPane.showMessageDialog(this,
        "¡Respuesta correcta!\n"
        + "Tu identidad ha sido verificada correctamente.\n"
        + "Ya puedes continuar con tu acceso.",
        "Acceso recuperado",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        }
        else {
            jPasswordField1.setEchoChar('•');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void iniciarsecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarsecionActionPerformed
        // TODO add your handling code here:
   int respuesta = JOptionPane.showConfirmDialog(this,
        "¿Realmente quieres abandonar esta página?\n"
        + "Se borrará lo que acabas de ingresar y tendrás que volver a hacerlo de nuevo.",
        "Confirmar salida",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);

if (respuesta == JOptionPane.YES_OPTION) {
    this.dispose();
    new Bienvenida().setVisible(true);
}
    }//GEN-LAST:event_iniciarsecionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loginTrab().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciarsecion;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
